from BaseClasses import Item, ItemClassification
from typing import NamedTuple

class AUSItemData(NamedTuple):
    id: int
    classification: ItemClassification

item_table = {
    "Jump Upgrade": AUSItemData(272001, ItemClassification.progression),
    "Jump Upgrade": AUSItemData(272002, ItemClassification.progression),
    "Jump Upgrade": AUSItemData(272003, ItemClassification.progression),
    "Red Energy": AUSItemData(272004, ItemClassification.progression),
    "Lucky Pots": AUSItemData(272005, ItemClassification.progression), # V1, maybe change to useful later
    "Double Jump Upgrade": AUSItemData(272006, ItemClassification.progression),
    "Double Jump Upgrade": AUSItemData(272007, ItemClassification.progression),
    "Double Jump Upgrade": AUSItemData(272008, ItemClassification.progression),
    "Duck": AUSItemData(272009, ItemClassification.progression),
    "Progressive Ceiling Stick": AUSItemData(272010, ItemClassification.progression),
    "Progressive Ceiling Stick": AUSItemData(272011, ItemClassification.progression),
    # "Teleport": AUSItemData(272012, ItemClassification.progression), # given automatically
    "Smash": AUSItemData(272013, ItemClassification.useful),
    "Fire Shot Upgrade": AUSItemData(272014, ItemClassification.progression),
    "Fire Shot Upgrade": AUSItemData(272015, ItemClassification.progression),
    "Yellow Energy": AUSItemData(272016, ItemClassification.progression),
    "Hatch": AUSItemData(272017, ItemClassification.progression),
    "Extra Air Capacity": AUSItemData(272018, ItemClassification.progression),
    "Extra Air Capacity": AUSItemData(272019, ItemClassification.progression),
    "Money Magnet": AUSItemData(272020, ItemClassification.useful),
    "Ice Shot": AUSItemData(272021, ItemClassification.progression),
    "Toughness Upgrade": AUSItemData(272022, ItemClassification.progression),
    "Toughness Upgrade": AUSItemData(272023, ItemClassification.progression),
    "Toughness Upgrade": AUSItemData(272024, ItemClassification.progression),
    "Heart": AUSItemData(272101, ItemClassification.useful),
    "Heart": AUSItemData(272102, ItemClassification.useful),
    "Heart": AUSItemData(272103, ItemClassification.useful),
    "Heart": AUSItemData(272104, ItemClassification.useful),
    "Heart": AUSItemData(272105, ItemClassification.useful),
    "Heart": AUSItemData(272106, ItemClassification.useful),
    "Heart": AUSItemData(272107, ItemClassification.useful),
    "Heart": AUSItemData(272108, ItemClassification.useful),
    "Heart": AUSItemData(272109, ItemClassification.useful),
    "Heart": AUSItemData(272110, ItemClassification.useful),
    "Heart": AUSItemData(272111, ItemClassification.useful),
    "Heart": AUSItemData(272112, ItemClassification.useful),
    "Heart": AUSItemData(272113, ItemClassification.useful),
    "Heart": AUSItemData(272114, ItemClassification.useful),
    "Heart": AUSItemData(272115, ItemClassification.useful),
    "Heart": AUSItemData(272116, ItemClassification.useful),
    "Heart": AUSItemData(272117, ItemClassification.useful),
    "Heart": AUSItemData(272118, ItemClassification.useful),
    "Heart": AUSItemData(272119, ItemClassification.useful),
    "Heart": AUSItemData(272120, ItemClassification.useful),
    "Heart": AUSItemData(272121, ItemClassification.useful),
    "Heart": AUSItemData(272122, ItemClassification.useful),
    "Heart": AUSItemData(272123, ItemClassification.useful),
    "Heart": AUSItemData(272124, ItemClassification.useful),
    "Heart": AUSItemData(272125, ItemClassification.useful),
    "Heart": AUSItemData(272126, ItemClassification.useful),
    "Heart": AUSItemData(272127, ItemClassification.useful),
    "Heart": AUSItemData(272128, ItemClassification.useful),
    "Heart": AUSItemData(272129, ItemClassification.useful),
    "Heart": AUSItemData(272130, ItemClassification.useful),
    "Heart": AUSItemData(272131, ItemClassification.useful),
    "Heart": AUSItemData(272132, ItemClassification.useful),
    "Heart": AUSItemData(272133, ItemClassification.useful),
    "Heart": AUSItemData(272134, ItemClassification.useful),
    "Heart": AUSItemData(272135, ItemClassification.useful),
    "Heart": AUSItemData(272136, ItemClassification.useful),
    "Heart": AUSItemData(272137, ItemClassification.useful),
    "Heart": AUSItemData(272138, ItemClassification.useful),
    "Heart": AUSItemData(272139, ItemClassification.useful),
    "Heart": AUSItemData(272140, ItemClassification.useful),
    "Heart": AUSItemData(272141, ItemClassification.useful),
    "Heart": AUSItemData(272142, ItemClassification.useful),
    "Heart": AUSItemData(272143, ItemClassification.useful),
    "Heart": AUSItemData(272144, ItemClassification.useful),
    "Heart": AUSItemData(272145, ItemClassification.useful),
    "Heart": AUSItemData(272146, ItemClassification.useful),
    "Heart": AUSItemData(272147, ItemClassification.useful),
    "Heart": AUSItemData(272148, ItemClassification.useful),
    "Heart": AUSItemData(272149, ItemClassification.useful),
    "Heart": AUSItemData(272150, ItemClassification.useful),
    "Heart": AUSItemData(272151, ItemClassification.useful),
    "Heart": AUSItemData(272152, ItemClassification.useful),
    "Heart": AUSItemData(272153, ItemClassification.useful),
    "Heart": AUSItemData(272154, ItemClassification.useful),
    "Heart": AUSItemData(272155, ItemClassification.useful),
    "Heart": AUSItemData(272156, ItemClassification.useful),
    "Heart": AUSItemData(272157, ItemClassification.useful),
    "Heart": AUSItemData(272158, ItemClassification.useful),
    "Heart": AUSItemData(272159, ItemClassification.useful),
    "Heart": AUSItemData(272160, ItemClassification.useful),
    "Heart": AUSItemData(272161, ItemClassification.useful),
    "Heart": AUSItemData(272162, ItemClassification.useful),
    "Heart": AUSItemData(272163, ItemClassification.useful),
    "Heart": AUSItemData(272164, ItemClassification.useful),
    "Heart": AUSItemData(272165, ItemClassification.useful),
    "Heart": AUSItemData(272166, ItemClassification.useful),
    "Heart": AUSItemData(272167, ItemClassification.useful),
    "Heart": AUSItemData(272168, ItemClassification.useful),
    "Heart": AUSItemData(272169, ItemClassification.useful),
    "Heart": AUSItemData(272170, ItemClassification.useful),
    "Heart": AUSItemData(272171, ItemClassification.useful),
    "Heart": AUSItemData(272172, ItemClassification.useful),
    "Heart": AUSItemData(272173, ItemClassification.useful),
    "Heart": AUSItemData(272174, ItemClassification.useful),
    "Heart": AUSItemData(272175, ItemClassification.useful),
    "Heart": AUSItemData(272176, ItemClassification.useful),
    "Heart": AUSItemData(272177, ItemClassification.useful),
    "Heart": AUSItemData(272178, ItemClassification.useful),
    "Heart": AUSItemData(272179, ItemClassification.useful),
    "Heart": AUSItemData(272180, ItemClassification.useful),
    "Heart": AUSItemData(272181, ItemClassification.useful),
    "Heart": AUSItemData(272182, ItemClassification.useful),
    "Heart": AUSItemData(272183, ItemClassification.useful),
    "Heart": AUSItemData(272184, ItemClassification.useful),
    "Heart": AUSItemData(272185, ItemClassification.useful),
    "Heart": AUSItemData(272186, ItemClassification.useful),
    "Heart": AUSItemData(272187, ItemClassification.useful),
    "Heart": AUSItemData(272188, ItemClassification.useful),
    "Heart": AUSItemData(272189, ItemClassification.useful),
    "Heart": AUSItemData(272190, ItemClassification.useful),
    "Heart": AUSItemData(272191, ItemClassification.useful),
    "Heart": AUSItemData(272192, ItemClassification.useful),
    "Heart": AUSItemData(272193, ItemClassification.useful),
    "Heart": AUSItemData(272194, ItemClassification.useful),
    "Heart": AUSItemData(272195, ItemClassification.useful),
    "Gold Orb": AUSItemData(272201, ItemClassification.progression),
    "Gold Orb": AUSItemData(272202, ItemClassification.progression),
    "Gold Orb": AUSItemData(272203, ItemClassification.progression),
    "Gold Orb": AUSItemData(272204, ItemClassification.progression),
    "Gold Orb": AUSItemData(272205, ItemClassification.progression),
    "Gold Orb": AUSItemData(272206, ItemClassification.progression),
    "Gold Orb": AUSItemData(272207, ItemClassification.progression),
    "Gold Orb": AUSItemData(272208, ItemClassification.progression),
    "Gold Orb": AUSItemData(272209, ItemClassification.progression),
    "Gold Orb": AUSItemData(272210, ItemClassification.progression),
    "Secret Flower": AUSItemData(272351, ItemClassification.progression),
    "Secret Flower": AUSItemData(272352, ItemClassification.progression),
    "Secret Flower": AUSItemData(272303, ItemClassification.progression),
    "Secret Flower": AUSItemData(272354, ItemClassification.progression),
    "Secret Flower": AUSItemData(272355, ItemClassification.progression),
    "Secret Flower": AUSItemData(272356, ItemClassification.progression),
    "Secret Flower": AUSItemData(272357, ItemClassification.progression),
    "Secret Flower": AUSItemData(272358, ItemClassification.progression),
    "Secret Flower": AUSItemData(272359, ItemClassification.progression),
    "Secret Flower": AUSItemData(272360, ItemClassification.progression),
    "Secret Flower": AUSItemData(272361, ItemClassification.progression),
    "Secret Flower": AUSItemData(272362, ItemClassification.progression),
    "Secret Flower": AUSItemData(272363, ItemClassification.progression),
    "Secret Flower": AUSItemData(272364, ItemClassification.progression),
    "Secret Flower": AUSItemData(272365, ItemClassification.progression),
    "Secret Flower": AUSItemData(272366, ItemClassification.progression),
    "Secret Flower": AUSItemData(272367, ItemClassification.progression),
    "Secret Flower": AUSItemData(272368, ItemClassification.progression),
    "Secret Flower": AUSItemData(272369, ItemClassification.progression),
    "Secret Flower": AUSItemData(272370, ItemClassification.progression),
    # V1, these might be progression later
    "Boss 1 Reward - 10 Crystals": AUSItemData(272401, ItemClassification.useful),
    "Boss 2 Reward - 25 Crystals": AUSItemData(272402, ItemClassification.useful),
    "Boss 3 Reward - 35 Crystals": AUSItemData(272403, ItemClassification.useful),
    "Boss 4 Reward - 35 Crystals": AUSItemData(272404, ItemClassification.useful),
    "Boss 5 Reward - 50 Crystals": AUSItemData(272405, ItemClassification.useful),
    "Boss 6 Reward - 75 Crystals": AUSItemData(272406, ItemClassification.useful),
    "Boss 7 Reward - 110 Crystals": AUSItemData(272407, ItemClassification.useful),
    "Boss 8 Reward - 65 Crystals": AUSItemData(272408, ItemClassification.useful),
    "Boss 9 Reward - 125 Crystals": AUSItemData(272409, ItemClassification.useful),
    "Boss 10 Reward - 180 Crystals": AUSItemData(272410, ItemClassification.useful),
    "Boss 11 Reward - 270 Crystals": AUSItemData(272411, ItemClassification.useful),
    "Boss 12 Reward - 150 Crystals": AUSItemData(272412, ItemClassification.useful),
    "Boss 13 Reward - 200 Crystals": AUSItemData(272413, ItemClassification.useful),
    "Boss 14 Reward - 200 Crystals": AUSItemData(272414, ItemClassification.useful),
    "Boss 15 Reward - 235 Crystals": AUSItemData(272415, ItemClassification.useful),
    "Boss 16 Reward - 150 Crystals": AUSItemData(272416, ItemClassification.useful),
    "Boss 17 Reward - 245 Crystals": AUSItemData(272417, ItemClassification.useful),
    "5 Flower Reward - 200 Crystals": AUSItemData(272418, ItemClassification.useful),
    "15 Flower Reward - 400 Crystals": AUSItemData(272419, ItemClassification.useful),
    "RainbowDive Reward - 300 Crystals": AUSItemData(272420, ItemClassification.useful),
    "RainbowDive Reward - 100 Crystals": AUSItemData(272421, ItemClassification.useful),
}