from typing import NamedTuple
from BaseClasses import Location

class LocData(NamedTuple):
    id: int
    region: str
class AUSLocation(Location):
    game: str = "An Untitled Story"
    
    # override constructor to automatically mark event locations as such
    def __init__(self, player: int, name = "", code = None, parent = None) -> None:
        super(AUSLocation, self).__init__(player, name, code, parent)
        self.event = code is None

location_table = {
    "Nightwalk_jump_1": LocData(72001, "Menu"),
    "Coldkeep_high_branch": LocData(72002, "Menu"),
    "Stonecastle_heart_door": LocData(72003, "Menu"),
    "Skytown_shop_6": LocData(72004, "Menu"),
    "Farfall_bottom_heart_door": LocData(72005, "Farfall"),
    "Grotto_djump": LocData(72006, "Menu"),
    "Skytown_pit_right": LocData(72007, "Menu"),
    "Firecage_top_left_gate": LocData(72008, "Firecage"),
    "Nightclimb_duck": LocData(72009, "Nightclimb"),
    "Coldkeep_boss": LocData(72010, "Menu"),
    "Skysand_bot_left": LocData(72011, "Skysand"),
    # "Skytown_tp": LocData(72012, "Menu"),
    "Stonecastle_rock_boss": LocData(72013, "Menu"),
    "Deeptower_cannon_boss": LocData(72014, "Menu"),
    "Skytown_shop_7": LocData(72015, "Menu"),
    "Firecage_boss": LocData(72016, "Firecage"),
    "Nightwalk_hatch": LocData(72017, "Menu"),
    "Deepdive_shaft": LocData(72018, "Deepdive"),
    "Deepdive_left_ceiling": LocData(72019, "Deepdive"),
    "Bonus_1": LocData(72020, "Firecage"),
    "Deepdive_shaft_mid_right": LocData(72021, "Deepdive"),
    "Deeptower_top_entrance": LocData(72022, "Curtain"),
    "Mountside_right_heart_door": LocData(72023, "Mountside"),
    "Strangecastle": LocData(72024, "Strangecastle"),
    "Deeptower_heart": LocData(72101, "Menu"),
    "Coldkeep_low_branch": LocData(72102, "Menu"),
    "Nightwalk_shrine_torches": LocData(72103, "Menu"),
    "Skytown_pit_left": LocData(72104, "Menu"),
    "Nightclimb_right_heart": LocData(72105, "Nightclimb"),
    "Nightclimb_wall_heart": LocData(72106, "Nightclimb"),
    "Grotto_mural_heart": LocData(72107, "Menu"),
    "Nightclimb_top_heart": LocData(72108, "Nightclimb"),
    "Skytown_tower_heart": LocData(72109, "Nightclimb"),
    "Skytown_red_heart": LocData(72110, "Menu"),
    "Skytown_yellow_heart": LocData(72111, "Menu"),
    "Skytown_shop_1": LocData(72112, "Menu"),
    "Skytown_shop_2": LocData(72113, "Menu"),
    "Skytown_shop_3": LocData(72114, "Menu"),
    "Skytown_shop_4": LocData(72115, "Menu"),
    "Skytown_shop_5": LocData(72116, "Menu"),
    "Nightwalk_sky_heart": LocData(72117, "Menu"),
    "Farfall_kill_3": LocData(72118, "Farfall"),
    "Stonecastle_hidden_heart": LocData(72119, "Menu"),
    "Nightwalk_block_heart": LocData(72120, "Menu"),
    "Farfall_yellow_heart_door": LocData(72121, "Farfall"),
    "Farfall_bottom_heart": LocData(72122, "Farfall"),
    "Firecage_top_heart_door": LocData(72123, "Firecage"),
    "Firecage_top": LocData(72124, "Firecage"),
    "Firecage_bot_left_secret": LocData(72125, "Firecage"),
    "Nightclimb_duck_heart": LocData(72126, "Nightclimb"),
    "Firecage_mid": LocData(72127, "Firecage"),
    "Firecage_mid_heart_door": LocData(72128, "Firecage"),
    "Firecage_bot": LocData(72129, "Firecage"),
    "Farfall_3_balloons": LocData(72130, "Farfall"),
    "Bottom_heart": LocData(72131, "Bottom"),
    "Coldkeep_cannon_heart": LocData(72132, "Menu"),
    "Stonecastle_top_heart": LocData(72133, "Menu"),
    "Farfall_5_balloons": LocData(72134, "Farfall"),
    "Bonus_2": LocData(72135, "Firecage"),
    "Deepdive_shaft_top_right": LocData(72136, "Deepdive"),
    "Skysand_right_heart_door": LocData(72137, "Skysand"),
    "Skysand_left_roof": LocData(72138, "Skysand"),
    "Skysand_top": LocData(72139, "Skysand"),
    "Skysand_top_heart_door": LocData(72140, "Skysand"),
    "Cloudrun_left_under": LocData(72141, "Bottom"),
    "Cloudrun_mid_save": LocData(72142, "Bottom"),
    "Cloudrun_far_right": LocData(72143, "Bottom"),
    "Deepdive_left": LocData(72144, "Deepdive"),
    "Deepdive_shaft_top": LocData(72145, "Deepdive"),
    "Nightwalk_shrine_heart": LocData(72146, "Menu"),
    "Farfall_chest": LocData(72147, "Farfall"),
    "Skysand_right_roof_chest": LocData(72148, "Skysand"),
    "Deepdive_chest": LocData(72149, "Deepdive"),
    "Nightclimb_chest": LocData(72150, "Nightclimb"),
    "Deepdive_right_path": LocData(72151, "Deepdive"),
    # "Skytown_astrocrash": LocData(72152, "Menu"), # Exclude?
    "Grotto_eye_boss": LocData(72153, "Deepdive"),
    "Darkgrotto_top_left": LocData(72154, "Darkgrotto"),
    "Darkgrotto_mid_right": LocData(72155, "Darkgrotto"),
    "Darkgrotto_boss_torch": LocData(72156, "Darkgrotto"),
    "Highlands_platform": LocData(72157, "Mountside"),
    "Nightwalk_upper_heart": LocData(72158, "Curtain"),
    "Curtain_break": LocData(72159, "Curtain"),
    "Nightwalk_chest": LocData(72160, "Curtain"),
    "Curtain_kill_4": LocData(72161, "Curtain"),
    # "Skytown_jumpbox": LocData(72162, "Menu"), # Exclude?
    # "Skytown_keep_going": LocData(72163, "Menu"), # Exclude?
    "Deepdive_exit_heart_mid": LocData(72164, "Deepdive2"),
    "Deepdive_exit_heart_top": LocData(72165, "Deepdive2"),
    "Icecastle_entrance": LocData(72166, "Curtain"),
    "Icecastle_left_outside": LocData(72167, "Curtain"),
    "Icecastle_entrance_heart_door": LocData(72168, "Curtain"),
    "Icecastle_low_mid_heartdoor": LocData(72169, "Curtain"),
    "Icecastle_high_mid_heartdoor": LocData(72170, "Curtain"),
    "Icecastle_top_left_heart_door": LocData(72171, "Curtain"),
    "Icecastle_top_right": LocData(72172, "Curtain"),
    "10_flowers": LocData(72173, "Curtain"),
    "20_flowers": LocData(72174, "Curtain"),
    "Rainbowdive_second_prize": LocData(72175, "Curtain"),
    "Rainbowdive_first_prize": LocData(72176, "Curtain"),
    "Icecastle_bottom_underhang": LocData(72177, "Curtain"),
    "Skylands_underhang": LocData(72178, "Curtain"),
    "Skylands_chest": LocData(72179, "Curtain"),
    "Skylands_duck": LocData(72180, "Curtain"),
    "Skylands_balloon_chain": LocData(72181, "Curtain"),
    "Skylands_portal": LocData(72182, "Mountside"),
    "Library_heart": LocData(72183, "Curtain"),
    "Deepdive_far_right": LocData(72184, "Deepdive2"),
    "Deepdive_shaft_bot_right": LocData(72185, "Deepdive"),
    "Blancland_top_left_kill": LocData(72186, "Blancland"),
    "Blancland_bottom_left": LocData(72187, "Blancland"),
    "Skylands_toll_gate": LocData(72188, "Curtain"),
    "Icecastle_low_mid_secret": LocData(72189, "Curtain"),
    "Blackcastle_top_mid": LocData(72190, "Blackcastle"),
    "Strangecastle_heart_door": LocData(72191, "Strangecastle"),
    "Skylands_heart_gate": LocData(72192, "Curtain"),
    "Undertomb_right_heart_door": LocData(72193, "Longbeach"),
    "Undertomb_left": LocData(72194, "Longbeach"),
    "Undertomb_left_heart_door": LocData(72195, "Longbeach"),
    "Skytown_shop_8": LocData(72201, "Menu"),
    "Farfall_blue_rock_boss": LocData(72202, "Farfall"),
    "Stonecastle_eye_boss": LocData(72203, "Menu"),
    "Skysand_boss": LocData(72204, "Skysand"),
    "Cloudrun_boss": LocData(72205, "Bottom"),
    "Deepdive_boss": LocData(72206, "Deepdive2"),
    "Darkgrotto_boss": LocData(72207, "Darkgrotto"),
    "Curtain_boss": LocData(72208, "Curtain"),
    "Icecastle_boss": LocData(72209, "Curtain"),
    "Blancland_boss": LocData(72210, "Blancland"),
    "Curtain_start_flower": LocData(72351, "Curtain"),
    "Longbeach_water_entrance_flower": LocData(72352, "Menu"),
    "Icecastle_entrance_flower": LocData(72353, "Curtain"),
    "Blancland_entrance_flower": LocData(72354, "Blancland"),
    "Stonecastle_flower": LocData(72355, "Menu"),
    "Farfall_bottom_flower": LocData(72356, "Farfall"),
    "Nightwalk_save_flower": LocData(72357, "Menu"),
    "Blackcastle_end_flower": LocData(72358, "Blackcastle"),
    "Nightclimb_flower": LocData(72359, "Nightclimb"),
    "Deepdive_boss_flower": LocData(72360, "Deepdive2"),
    "Bottom_flower": LocData(72361, "Bottom"),
    "Mountside_left_flower": LocData(72362, "Mountside"),
    "Library_flower": LocData(72363, "Curtain"),
    "Darkgrotto_bot_right_flower": LocData(72364, "Darkgrotto"),
    "Nightwalk_high_flower": LocData(72365, "Curtain"),
    "Cloudrun_start_flower": LocData(72366, "Bottom"),
    "Grotto_flower": LocData(72367, "Menu"),
    "Skysand_left_outside": LocData(72368, "Skysand"),
    "Skytown_flower": LocData(72369, "Menu"),
    "Nightwalk_nest_flower": LocData(72370, "Curtain"),
    "Grotto_boss_1": LocData(72401, "Menu"),
    "Deeptower_boss_2": LocData(72402, "Menu"),
    "Coldkeep_boss_3": LocData(72403, "Menu"),
    "Nightclimb_boss_4": LocData(72404, "Nightclimb"),
    "Stonecastle_boss_5": LocData(72405, "Menu"),
    "Grotto_boss_6": LocData(72406, "Deepdive"),
    "Firecage_boss_7": LocData(72407, "Firecage"),
    "Farfall_boss_8": LocData(72408, "Farfall"),
    "Stonecastle_boss_9": LocData(72409, "Menu"),
    "Skysand_boss_10": LocData(72410, "Skysand"),
    "Cloudrun_boss_11": LocData(72411, "Bottom"),
    "Deepdive_boss_12": LocData(72412, "Deepdive2"),
    "Darkgrotto_boss_13": LocData(72413, "Darkgrotto"),
    "Curtain_boss_14": LocData(72414, "Curtain"),
    "Icecastle_boss_15": LocData(72415, "Curtain"),
    "Blancland_boss_16": LocData(72416, "Blancland"),
    "Blackcastle_boss_17": LocData(72417, "Blackcastle"),
    "5_flowers": LocData(72418, "Curtain"),
    "15_flowers": LocData(72419, "Curtain"),
    "Rainbowdive_300": LocData(72420, "Curtain"),
    "Rainbowdive_100": LocData(72421, "Curtain"),
    "Victory": LocData(None, "Blackcastle")
}